
name: Docker Image CI

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
         name: Checkout
         uses: actions/checkout@main
      - 
         name: Change Screenshots Links
         run: sed -i 's#screenshot](images/#screenshot](https://github.com/zx900930/nyaarr/raw/main/images/#g' ./README.md
      - 
         name: Sync Readme
         uses: meeDamian/sync-readme@v1.0.6
         with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKER_PASS }}
          slug: ${{ secrets.DOCKERHUB_USERNAME }}/nyaarr
          readme: ./README.md
          description: Nyaarr, a bridge between Nyaa Anime and Sonarr
      - name: Docker meta
        id: meta_nyaarr # you'll use this in the next step
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            triatk/nyaarr
          # Docker tags based on the following events/attributes
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta_nyaarr.outputs.tags }}
          labels: ${{ steps.meta_nyaarr.outputs.labels }}
